name: "Tests"

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: read

# If a later version is pushed to the same branch cancel the currently running
# one.
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  run_tests:
    runs-on: "ubuntu-latest"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build container
      run: docker compose build

    - name: Prepare database
      run: docker compose run app mix ecto.create

    - name: Run Tests
      run: docker compose run app mix test

    - name: Stop running containers
      if: always()
      run: docker compose down
    